version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shopping-list"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-q22rxlo7ueii"
s3_prefix = "shopping-list"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
