AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  shopping-list-alexa

  SAM Template for shopping-list-alexa

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  ShoppingListFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: lambda_function.handler
      Runtime: python3.8
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter*
                - ssm:GetParametersByPath
                - ssm:PutParameter
              Resource: 'arn:aws:ssm:*:148243745686:parameter/shopping-list-alexa*'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            SkillId: amzn1.ask.skill.a0f71ee2-50a6-4802-968a-b903fa0de09b

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ShoppingListFunction:
    Description: "Shopping List Lambda Function ARN"
    Value: !GetAtt ShoppingListFunction.Arn
  ShoppingListFunctionIamRole:
    Description: "Implicit IAM Role created for Shopping List function"
    Value: !GetAtt ShoppingListFunctionRole.Arn
